name: untitled3
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.4
  google_sign_in: ^6.3.0
  http: ^1.3.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2   # Let it auto-pull firebase_auth_web 5.9.8
  cloud_firestore: ^5.6.6 # Matched to firebase_core
  cupertino_icons: ^1.0.8
  firebase_database: ^11.3.5
  fl_chart: ^0.71.0
  webview_flutter: ^4.0.0
  web: ^1.0.0
  js: ^0.6.7
  flutter_webview_plugin: ^0.4.0
  flutter_inappwebview: ^5.3.2
  url_launcher: ^6.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

