// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// File generated by Firebase CLI (firebase_options.dart).
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhEnxp_MEUOObmKMuBUCMFjPTWNSfGLSU',
    appId: '1:542063736785:web:1ef143847f9f37be9a92f0',
    messagingSenderId: '542063736785',
    projectId: 'smart-c7a94',
    authDomain: 'smart-c7a94.firebaseapp.com',
    storageBucket: 'smart-c7a94.firebasestorage.app',
    measurementId: 'G-ME42H9D09K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz_82v6TSJKNM4vl01L2gXUJ0ks8cKTGA',
    appId: '1:542063736785:android:5fea5d596e0a3a1e9a92f0',
    messagingSenderId: '542063736785',
    projectId: 'smart-c7a94',
    storageBucket: 'smart-c7a94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADYjv_4q_RZDGX8MMgN-78UQDfbiv_4Co',
    appId: '1:542063736785:ios:72c0f8141e04141e9a92f0',
    messagingSenderId: '542063736785',
    projectId: 'smart-c7a94',
    storageBucket: 'smart-c7a94.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADYjv_4q_RZDGX8MMgN-78UQDfbiv_4Co',
    appId: '1:542063736785:ios:72c0f8141e04141e9a92f0',
    messagingSenderId: '542063736785',
    projectId: 'smart-c7a94',
    storageBucket: 'smart-c7a94.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhEnxp_MEUOObmKMuBUCMFjPTWNSfGLSU',
    appId: '1:542063736785:web:50b28f40663063fd9a92f0',
    messagingSenderId: '542063736785',
    projectId: 'smart-c7a94',
    authDomain: 'smart-c7a94.firebaseapp.com',
    storageBucket: 'smart-c7a94.firebasestorage.app',
    measurementId: 'G-47DZTWN6XC',
  );
}
